    project:
  type: website
  output-dir: docs

website:
  title: "Proyecto Piña"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: resultados.qmd
        text: Resultados
      - href: discusion.qmd
        text: Discusión